### ISSUE TITLE
resolve_unc_paths="True" causes System.IO.IOException

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#110] opened 2015-06-03 14:37 UTC
When attempting to ship a local file via a UNC path using the new `resolve_unc_paths="True" ` ( #104  ) feature, as configured below:
```
<LogSearchShipper data_folder="C:\Apps\LogSearchShipper-DEV\data" resolve_unc_paths="True" 

			...
				<watch files="\\LON-WS01186\Logs\LogSearchShipper-DEV\EDB_expected_event_sources.log" type="json">
					...
```
LogSearchShipper fails to start; throwing the following `"System.IO.IOException","Message":"The process cannot access the file 'C:\\Logs\\LogSearchShipper-DEV\\EDB_expected_event_sources.log' because it is being used by another process.` error:

```
{"@timestamp":"2015-06-03T14:29:53.109Z","ClassName":"System.IO.IOException","Message":"The process cannot access the file 'C:\\Logs\\LogSearchShipper-DEV\\EDB_expected_event_sources.log' because it is being used by another process.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at LogSearchShipper.Core.NxLog.NxLogProcessManager.HasReadAccess(String folderPath)\r\n   at LogSearchShipper.Core.NxLog.NxLogProcessManager.PrepareFilePaths(String val)\r\n   at LogSearchShipper.Core.NxLog.NxLogProcessManager.GenerateNormalFileWatchConfig(FileWatchElement inputFile, Int32 i)\r\n   at LogSearchShipper.Core.NxLog.NxLogProcessManager.GenerateInputFilesConfig()\r\n   at LogSearchShipper.Core.NxLog.NxLogProcessManager.SetupConfigFile()\r\n   at LogSearchShipper.Core.NxLog.NxLogProcessManager.Start()\r\n   at LogSearchShipper.Core.LogSearchShipperProcessManager.Start()\r\n   at LogSearchShipper.LogSearchShipperService.Start(HostControl hostControl)\r\n   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Start(HostControl hostControl)\r\n   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nWinIOError\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.IO.__Error\nVoid WinIOError(Int32, System.String)","HResult":-2147024864,"Source":"mscorlib","WatsonBuckets":null,"logger":"Topshelf.Runtime.Windows.WindowsServiceHost","level":"FATAL"}
```

**Comment by fandrei** [comment] 2015-06-03 14:39
@mrdavidlaing, isn't there an extra instance of LSS or nxlog process running?

**Comment by mrdavidlaing** [comment] 2015-06-03 14:40
Yes, but none that is attempting to ship this file

**Comment by fandrei** [comment] 2015-06-04 04:50
@mrdavidlaing, unfortunately I can't reproduce this, but I've fixed one possible case. Could you try this? https://github.com/cityindex/LogSearchShipper/pull/111

**Closed** 2015-06-05 09:09 UTC
